upes-open/OSoC-25-FormEase

- styles.css
- toolbox.html
Made a Toolbox in toolbox.html file with functionable dropdown, and buttons like resize, compress, convert and preview.
Added internal script in toolbox.html for making dropdown dynamic and functional.
Range type input available for resize.
Used Tailwind CSS for styling and a bit of custom styling in styles.css.
Responsive UI.
> #6 ArpitKaushik2025: Build Toolbox Structure with Tailwind Styling and a bit of Custom Styling

- content.js
- manifest.json
- styles.css
- test.html
- toolbox.html
Updated manifest.json to serve the toolbox.
Fixed the fetch logic in content.js.
Fixed the setupToolboxEventListeners function in content.js.
Improved styling for toolbox.
Added scale display for resize range.
Added dropdown for converting format.
Added input field for compress percentage.
Changed the compress, resize, convert buttons to just one button Apply.
> Fix: #17 ArpitKaushik2025: Fix Toolbox UI and rendering

- content.js
- styles.css
- toolbox.html
Decluttered the toolbox.html file with unnecessary JS code.
Resize scale display was visible even on changing the option to compress or resize. Fixed that.
Implemented functionality of closing the toolbox on clicking the submit buttons.
Fixed the issue of creation of multiple toolboxes on changing the file.
> fix: Fixes #29 ArpitKaushik2025/feat: fix toolbar bug

- content.js
- test.html
Problem : Not showing the preview of the image when user add the image or document 
Solution : Created a preview container, did necessary changes function which it requires, mainly there was problem that file was not provided as arguments and used inputId which was fine can create issue in future so instead of that I used data-set and created formEaseId which is unique for every time.
> fix: added the preview part and fix file passing for all inputs

- toolbox.html
- Added file input under the Resize section
- Prevented Apply button from submitting without file selection
- Tested manually and resolves Issue #36
> Fix: Add file input and validation for Resize Apply button (Issue #36)

- content.js
- test.html
This PR addresses the issue of conditional toolbox injection in content.js, ensuring it aligns with the updated test.html requirements. The toolbox now appears only for image fields (Resize, Compress, Convert) with specific validations, and is suppressed for PDF fields. Changes include dynamic ID handling, validation-aware processing, and event listener safeguards.
> issue resolved #44

- content.js
- test.html
- toolbox.html
Changes made :
1. Show Resolution and final size
2. Shows original size and resolution as well
3. Shows percentage saved
I made the necessary changes in the code, just am not able to test it because apply button is not working well, it is showing alert of file submission which is not going even on pressing ok, I cannot understand the glitch, I am open to any changes you can suggest, I will fix them promptly.
Fix: #61
> Fix: #61/ ArpitKaushik2025/Resolution Display

- content.js
- styles.css
- toolbox.html
Added manual dimension inputs in toolbox.html
Input validated in toolbox.html script, not needed in content.js
Resized image will display the manual input size, once it is up and working, that functionality.
Adding picture for better reviewing
Fix : #63
> Fix: #63/ArpitKaushik2025/Manual Image Dimensions

- content.js
- manifest.json
- styles.css
Problem : Edit Button was exiting but not working, user not able to use toolbox by clicking edit button
Solution : Fix the error by changing the exiting logics in injectFloatingEditButton() function, made it async aware previous it was not able to handle it. created functions to work in shadow DOM, load all the data asynchronously. now we can see the edit button as well as we can use toolbox also.
on a separate note : there are other issue like the background color convert into white for dark theme by default, in the google form the edit button comes inside the insert file container. there is a bug related to edit button its not in proper position
> fix: edit button and toolbar not showing due to missing setup

- toolbox.html
> #94 - Resize Slider Should Reset to 100% After Apply

- content.js
- manifest.json
- styles.css
now its fixed i tested in various sites 
if any changes please do let me please ma'am
> #106 - Global CSS from Extension Breaks Host Site Styles (e.g., ChatGPT Dark Mode)

- content.js
- manifest.json
- scripts/compress.js
- scripts/convert.js
- scripts/reset.js
- scripts/resize.js
- styles.css
- toolbox.html
This PR fixes the issue of same feedback area being used for all operations by changing and dedicating a particular div for feedbacks.
Also fixed a minor bug of last PR, removing of css from manifest.json, which is removing style of floating edit button, i suggest it to be fixed by adding styling which changes on system theme.
Fix: #107
> Fix:#107 ArpitKaushik2025/refactor feedback

- .gitignore
- content.js
- manifest.json
- scripts/compressPDF.js
- scripts/pdf-lib.min.js
- scripts/pica.min.js
Added minified code of pdf-lib and created compressPDF.js file.
Updated manifest.json to provide both files.
Updated content.js to inject these scripts.
Checked loading of library and compressPDF.js file.
Fix : #112
> Fix: #112/ feat: Configure pdf-lib

- content.js
updated the checkToolboxExistence() and applied all the conditions mentioned in the issue discription
if you find some mistakes or problem please do let me know ma'am.
> #115 - Detect Uploaded File Type (Image / PDF / Video)

- content.js
updated the setupToolboxEventListeners() and applied all the conditions mentioned in the issue discription
if you find some mistakes or problem please do let me know ma'am.
> #116 - Show Toolbox Options Dynamically Based on File Type

- content.js
- toolbox.html
Hi @vatssomya mam. I’ve completed the changes for this issue and submitted a PR. Kindly review it whenever you get time. Would love your feedback as I’m new to open source. Thank you! 😊
> Add separate feedback containers for PDF and video in toolbox.html

- content.js
Fixed toolbox UI for video files.
Fix: #134
> Fix: #134/feat: Fix Toolbox UI video

- content.js
- toolbox.html
done with the changes now have different div for video preview and trim logic for any changes please do let me know ma'am
> #158 - Separate Video Preview and Feedback Containers in Trim Video Flow

- content.js
Fixed log errors of compression PDF and  moved logic to compressPDF.js from content.js.
Fix: #169
> Fix: #169/ feat: Fixed console logs for compression PDF

- scripts/compressVideo.js
- scripts/reset.js
Toolbox will now auto close with a delay of 3 seconds after operation is performed of Sae Changes.
Fix: #168
> Fix: #168/ Arpit kaushik2025/auto close toolbox

- content.js
so problem was that many sites only create <input type="file"> on button click. So we have to wait so added a delay there
> #166 - Investigate Resize Tool Not Working Across All Platforms
